2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_224432-bmkwbxf3/logs/debug.log
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_224432-bmkwbxf3/logs/debug-internal.log
2023-02-11 22:44:32,844 INFO    MainThread:1514 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f81a9266bf0>
2023-02-11 22:44:32,845 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:44:32,845 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:44:32,845 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:44:32,845 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:44:32,854 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:44:32,855 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:44:32,862 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:44:32,862 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:44:32,862 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:44:32,929 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:44:33,410 INFO    MainThread:1514 [wandb_run.py:_on_init():2121] communicating current version
2023-02-11 22:44:33,518 INFO    MainThread:1514 [wandb_run.py:_on_init():2125] got version response upgrade_message: "wandb version 0.13.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-02-11 22:44:33,519 INFO    MainThread:1514 [wandb_init.py:init():758] starting run threads in backend
2023-02-11 22:44:37,492 WARNING MainThread:1514 [wandb_init.py:init():1129] interrupted
Traceback (most recent call last):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 770, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_224511-12r52bc4/logs/debug.log
2023-02-11 22:45:11,357 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_224511-12r52bc4/logs/debug-internal.log
2023-02-11 22:45:11,358 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:45:11,358 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:45:11,358 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:45:11,358 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:45:11,368 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:45:11,369 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:45:11,376 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:45:11,376 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:45:11,376 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:45:11,430 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:45:11,847 INFO    MainThread:1514 [wandb_run.py:_on_init():2121] communicating current version
2023-02-11 22:45:11,964 WARNING MsgRouterThr:1514 [router.py:_handle_msg_rcv():114] No listener found for msg with uuid 9b3eb1b4a40545b4a11ce3af69625877 (control {
  req_resp: true
  local: true
  relay_id: "a7f1c419061b4f08899a9a712c26d595"
}
uuid: "9b3eb1b4a40545b4a11ce3af69625877"
response {
  check_version_response {
    upgrade_message: "wandb version 0.13.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"
  }
}
)
2023-02-11 22:45:11,965 WARNING MsgRouterThr:1514 [router.py:message_loop():77] message_loop has been closed
2023-02-11 22:45:16,855 INFO    MainThread:1514 [wandb_run.py:_on_init():2125] got version response None
2023-02-11 22:45:16,856 INFO    MainThread:1514 [wandb_init.py:init():758] starting run threads in backend
2023-02-11 22:45:47,041 INFO    MainThread:1514 [wandb_run.py:_console_start():2101] atexit reg
2023-02-11 22:45:47,043 INFO    MainThread:1514 [wandb_run.py:_redirect():1959] redirect: SettingsConsole.WRAP_RAW
2023-02-11 22:45:47,043 INFO    MainThread:1514 [wandb_run.py:_redirect():2024] Wrapping output streams.
2023-02-11 22:45:47,043 INFO    MainThread:1514 [wandb_run.py:_redirect():2046] Redirects installed.
2023-02-11 22:45:47,044 INFO    MainThread:1514 [wandb_init.py:init():798] run started, returning control to user process
2023-02-11 22:45:47,644 INFO    MainThread:1514 [wandb_run.py:_finish():1844] finishing run iyngkarrankumar/AVR/12r52bc4
2023-02-11 22:45:47,644 INFO    MainThread:1514 [wandb_run.py:_atexit_cleanup():2070] got exitcode: 0
2023-02-11 22:45:47,644 INFO    MainThread:1514 [wandb_run.py:_restore():2053] restore
2023-02-11 22:45:47,645 INFO    MainThread:1514 [wandb_run.py:_restore():2059] restore done
2023-02-11 22:56:07,462 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225607-f1dgmntq/logs/debug.log
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225607-f1dgmntq/logs/debug-internal.log
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:56:07,463 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:56:07,473 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:56:07,474 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:56:07,479 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:56:07,480 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:56:07,480 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:56:07,617 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:56:53,463 WARNING MainThread:1514 [wandb_init.py:init():1129] interrupted
Traceback (most recent call last):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-02-11 22:57:46,885 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Configure stats pid to 1514
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/.config/wandb/settings
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/settings
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'masking.ipynb', 'program': '/Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/masking.ipynb'}
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_init.py:_log_setup():478] Logging user logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225746-v7eups46/logs/debug.log
2023-02-11 22:57:46,886 INFO    MainThread:1514 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/iyngkarrankumar/Documents/AI/AVR-functional-modularity/wandb/run-20230211_225746-v7eups46/logs/debug-internal.log
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():518] calling init triggers
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():571] starting backend
2023-02-11 22:57:46,887 INFO    MainThread:1514 [wandb_init.py:init():575] setting up manager
2023-02-11 22:57:46,895 INFO    MainThread:1514 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-02-11 22:57:46,896 INFO    MainThread:1514 [wandb_init.py:init():582] backend started and connected
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1202] probe notebook
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_run.py:_label_probe_notebook():1212] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-02-11 22:57:46,902 INFO    MainThread:1514 [wandb_init.py:init():670] updated telemetry
2023-02-11 22:57:46,954 INFO    MainThread:1514 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-11 22:58:47,202 ERROR   MainThread:1514 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-02-11 22:58:47,231 ERROR   MainThread:1514 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/iyngkarrankumar/opt/anaconda3/envs/DLenv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
